# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@5

jobs:
  # First job declared is for building things..
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing Dependencies.."
      - run: npm install
      - run: echo "Building things..."
  # Second job declared is for launching unit tests with Jest
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - run: echo "Installing dependencies for unit tests..."
      - run: npm install
      - run:
          command: npm install jest-junit
      - run: echo "Running unit tests..."
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/


  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies for integration tests.."
#      - run: npm install
      - run: echo "Running integration tests..."

  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies for security tests.."
#      - run: npm install
      - run: echo "Running Security Tests..."


  # Deploy development environment
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_int:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to integration environment..."

  # Deploy production environment
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^feature\/.*/
                - /^hotfix\/.*/

      - unit_tests:
          requires:
            - build

      - integration_tests:
          requires:
            - unit_tests

      - security_tests:
          requires:
            - build

      - deploy_dev:
          requires:
            - integration_tests
            - security_tests

      - deploy_int:
          requires:
            - integration_tests
            - security_tests

      - deploy_prod:
          requires:
            - deploy_dev
          filters:
            branches:
              only: master