version: 2.1

orbs:
  node: circleci/node@5

executors:
  default:
    docker:
      - image: circleci:node:16

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Code Linting
          command: npm run lint
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Package
          command: npm run package

  unit_tests:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm install jest-junit
      - run:
          name: Run Unit Tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  integration_tests:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm run test:integration

  security_tests:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm audit --audit-level=high


  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_int:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to integration environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
        filters:
          branches:
            ignore:
                  - /^hotfix\/.*/
                  - /^feature\/.*/
      - unit_tests:
          requires:
            - build

      - integration_tests:
          requires:
            - unit_tests

      - security_tests:
          required:
            - build

      - deploy_dev:
          requires:
            - integration_tests
            - security_tests
            - unit_tests
          filters:
            branches:
              only:
                - develop

      - deploy_int:
          requires:
            - integration_tests
            - security_tests
          filters:
            branches:
              only:
                - integration

      - deploy_prod:
          requires:
            - deploy_int
            - deploy_dev
          filters:
            branches:
              only:
                - main