# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@5

jobs:
  # First job declared is for building things..
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing Dependencies.."
      - run: echo "Installing dependencies..."
#      - run: npm install
      - run: echo "Running code analysis..."
#      - run: npm run lint
      - run: echo "Cleaning and packaging..."
#      - run: npm run build
  # Second job declared is for launching unit tests with Jest
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - run: echo "Installing dependencies for unit tests..."
      - run: npm install
      - run:
          command: npm install jest-junit
      - run: echo "Running unit tests..."
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/


  integration_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies for integration tests.."
#      - run: npm install
      - run: echo "Running integration tests..."

  performance_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running performance tests..."

  compatibility_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running compatibility tests..."

    accessibility_tests:
      executor: node/default
      steps:
        - checkout
        - run: echo "Running accessibility tests..."

  security_tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies for security tests.."
#      - run: npm install
      - run: echo "Running Security Tests..."


  # Deploy development environment
  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing development deployment..."
      - run: echo "Deploying to development environment..."
      - run: echo "Running verification tests..."
      - run: echo "Monitoring development deployment..."

  deploy_int:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing integration deployment..."
      - run: echo "Deploying to integration environment..."
      - run: echo "Running functional validation tests..."
      - run: echo "Running load tests..."
      - run: echo "Monitoring integration deployment..."

  # Deploy production environment
  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Preparing production deployment..."
      - run: echo "Deploying to production environment..."
      - run: echo "Running final validation checks..."
      - run: echo "Monitoring production deployment..."

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^feature\/.*/
                - /^hotfix\/.*/

      - unit_tests:
          requires:
            - build

      - integration_tests:
          requires:
            - unit_tests

      - security_tests:
          requires:
            - build

      - performance_tests:
          requires:
            - integration_tests

      - compatibility_tests:
          requires:
            - integration_tests

      - accessibility_tests:
          requires:
            - integration_tests

      - deploy_dev:
          requires:
            - performance_tests
            - compatibility_tests
            - accessibility_tests
          filters:
            branches:
              only: develop

      - deploy_int:
          requires:
            - deploy_dev
          filters:
            branches:
              only: integration

      - deploy_prod:
          requires:
            - deploy_int
          filters:
            branches:
              only: master
